### ISSUE TITLE
Story 24: Changing permission to view does not change until refresh of page.

### ISSUE THREAD

**Issue by Rolo123y** [MayyarAA/studentplanner#52]
**Bug:** In the 'listView' page, when 'sharing' and editing the users permission,  the permission changes but does not update until the user refreshes the page.

**Steps to replicate:**
1. Log-in as a user: 
            user: Wmmeyer
            Pass: 342Group8!?
2. View the Board called 'MyBoard'
3. Click the button 'Sharing'
4. Edit the permission to 'view' and click the button 'Update'
5. The database it updated with the new permission but the board is not updated until a refresh occurs

**Potential Fix:** When updating the permission, also redirect to the same page.

**Comment by williamj2543** [comment]
Fixed
