### ISSUE TITLE
Story 24: Owner of a board can change their own permission

### ISSUE THREAD

**Issue by Rolo123y** [MayyarAA/studentplanner#53]
**Bug:** When a user creates a Board, they initially have a permission of 'edit'. The user can change their own permission to 'view' allowing them to lose edit access to their own board.

**Steps to replicate:**
1. log-in to a user account
                             User: Wmmeyer
                             Pass: 342Group8!?
2. Select the Board called 'MyBoard'
3. Click the button called 'Sharing'
4. The board owner (Wmmeyer) can see their name and edit permission/ are able to change their edit permission

**potential fix**: Remove the board owners name when changing permissions of users who have access to the board.

**Comment by williamj2543** [comment]
Fixed, you cannot change your own permission now.
