### ISSUE TITLE
Delete Task routes to older version of board

### ISSUE THREAD

**Issue by gaurav613** [MayyarAA/studentplanner#58]
In the latest main branch, when a task is deleted from a list, the application is displaying an **older version** of the board - which was designed from Sprint 2. I'm guessing that just the routing needs to be changed accordingly to display the current updated board to the user.

**Comment by Rolo123y** [comment]
This is not really a bug. The code has a line that routes to the Demo code. If your code is in a file inside the Demo code which it should be, you need to include this file to route to your code. For the Demo, this is working as intended.
